/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API for Fake Image Detection — verifies if uploaded images are real or AI-generated.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AnalyzeImageBody,
  ConfidenceBucket,
  ErrorResponse,
  GetStatsTimeseriesParams,
  HealthStatus,
  ListScansParams,
  Scan,
  Stats,
  TimeseriesPoint,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns the most recent image scans, newest first.
 * @summary List recent image scans
 */
export const getListScansUrl = (params?: ListScansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/scans?${stringifiedParams}`
    : `/api/scans`;
};

export const listScans = async (
  params?: ListScansParams,
  options?: RequestInit,
): Promise<Scan[]> => {
  return customFetch<Scan[]>(getListScansUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListScansQueryKey = (params?: ListScansParams) => {
  return [`/api/scans`, ...(params ? [params] : [])] as const;
};

export const getListScansQueryOptions = <
  TData = Awaited<ReturnType<typeof listScans>>,
  TError = ErrorType<unknown>,
>(
  params?: ListScansParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listScans>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListScansQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listScans>>> = ({
    signal,
  }) => listScans(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listScans>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListScansQueryResult = NonNullable<
  Awaited<ReturnType<typeof listScans>>
>;
export type ListScansQueryError = ErrorType<unknown>;

/**
 * @summary List recent image scans
 */

export function useListScans<
  TData = Awaited<ReturnType<typeof listScans>>,
  TError = ErrorType<unknown>,
>(
  params?: ListScansParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listScans>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListScansQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Accepts an image upload, runs the fake-image-detection model, and returns the prediction.
 * @summary Analyze an uploaded image for authenticity
 */
export const getAnalyzeImageUrl = () => {
  return `/api/scans`;
};

export const analyzeImage = async (
  analyzeImageBody: AnalyzeImageBody,
  options?: RequestInit,
): Promise<Scan> => {
  const formData = new FormData();
  formData.append(`image`, analyzeImageBody.image);

  return customFetch<Scan>(getAnalyzeImageUrl(), {
    ...options,
    method: "POST",
    body: formData,
  });
};

export const getAnalyzeImageMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof analyzeImage>>,
    TError,
    { data: BodyType<AnalyzeImageBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof analyzeImage>>,
  TError,
  { data: BodyType<AnalyzeImageBody> },
  TContext
> => {
  const mutationKey = ["analyzeImage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof analyzeImage>>,
    { data: BodyType<AnalyzeImageBody> }
  > = (props) => {
    const { data } = props ?? {};

    return analyzeImage(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnalyzeImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof analyzeImage>>
>;
export type AnalyzeImageMutationBody = BodyType<AnalyzeImageBody>;
export type AnalyzeImageMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Analyze an uploaded image for authenticity
 */
export const useAnalyzeImage = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof analyzeImage>>,
    TError,
    { data: BodyType<AnalyzeImageBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof analyzeImage>>,
  TError,
  { data: BodyType<AnalyzeImageBody> },
  TContext
> => {
  return useMutation(getAnalyzeImageMutationOptions(options));
};

/**
 * @summary Get a single scan by id
 */
export const getGetScanUrl = (id: string) => {
  return `/api/scans/${id}`;
};

export const getScan = async (
  id: string,
  options?: RequestInit,
): Promise<Scan> => {
  return customFetch<Scan>(getGetScanUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetScanQueryKey = (id: string) => {
  return [`/api/scans/${id}`] as const;
};

export const getGetScanQueryOptions = <
  TData = Awaited<ReturnType<typeof getScan>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getScan>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetScanQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getScan>>> = ({
    signal,
  }) => getScan(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getScan>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetScanQueryResult = NonNullable<
  Awaited<ReturnType<typeof getScan>>
>;
export type GetScanQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get a single scan by id
 */

export function useGetScan<
  TData = Awaited<ReturnType<typeof getScan>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getScan>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetScanQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Aggregate detection stats for the dashboard
 */
export const getGetStatsUrl = () => {
  return `/api/stats`;
};

export const getStats = async (options?: RequestInit): Promise<Stats> => {
  return customFetch<Stats>(getGetStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetStatsQueryKey = () => {
  return [`/api/stats`] as const;
};

export const getGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({
    signal,
  }) => getStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStats>>
>;
export type GetStatsQueryError = ErrorType<unknown>;

/**
 * @summary Aggregate detection stats for the dashboard
 */

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Daily breakdown of real vs fake scans
 */
export const getGetStatsTimeseriesUrl = (params?: GetStatsTimeseriesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/stats/timeseries?${stringifiedParams}`
    : `/api/stats/timeseries`;
};

export const getStatsTimeseries = async (
  params?: GetStatsTimeseriesParams,
  options?: RequestInit,
): Promise<TimeseriesPoint[]> => {
  return customFetch<TimeseriesPoint[]>(getGetStatsTimeseriesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetStatsTimeseriesQueryKey = (
  params?: GetStatsTimeseriesParams,
) => {
  return [`/api/stats/timeseries`, ...(params ? [params] : [])] as const;
};

export const getGetStatsTimeseriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getStatsTimeseries>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStatsTimeseriesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getStatsTimeseries>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStatsTimeseriesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStatsTimeseries>>
  > = ({ signal }) => getStatsTimeseries(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStatsTimeseries>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStatsTimeseriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStatsTimeseries>>
>;
export type GetStatsTimeseriesQueryError = ErrorType<unknown>;

/**
 * @summary Daily breakdown of real vs fake scans
 */

export function useGetStatsTimeseries<
  TData = Awaited<ReturnType<typeof getStatsTimeseries>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStatsTimeseriesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getStatsTimeseries>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStatsTimeseriesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Confidence score distribution buckets
 */
export const getGetConfidenceDistributionUrl = () => {
  return `/api/stats/confidence`;
};

export const getConfidenceDistribution = async (
  options?: RequestInit,
): Promise<ConfidenceBucket[]> => {
  return customFetch<ConfidenceBucket[]>(getGetConfidenceDistributionUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetConfidenceDistributionQueryKey = () => {
  return [`/api/stats/confidence`] as const;
};

export const getGetConfidenceDistributionQueryOptions = <
  TData = Awaited<ReturnType<typeof getConfidenceDistribution>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getConfidenceDistribution>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetConfidenceDistributionQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getConfidenceDistribution>>
  > = ({ signal }) => getConfidenceDistribution({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getConfidenceDistribution>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetConfidenceDistributionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getConfidenceDistribution>>
>;
export type GetConfidenceDistributionQueryError = ErrorType<unknown>;

/**
 * @summary Confidence score distribution buckets
 */

export function useGetConfidenceDistribution<
  TData = Awaited<ReturnType<typeof getConfidenceDistribution>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getConfidenceDistribution>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetConfidenceDistributionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
