/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API for Fake Image Detection — verifies if uploaded images are real or AI-generated.
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export type Verdict = (typeof Verdict)[keyof typeof Verdict];

export const Verdict = {
  real: "real",
  fake: "fake",
} as const;

export interface Signal {
  /** Human-readable signal name */
  name: string;
  /** Signal score on a 0–100 scale (higher = more suspicious of being fake) */
  score: number;
  /** Relative weight of this signal in the final verdict, 0–1 */
  weight: number;
  /** Short explanation of what this signal measures */
  description: string;
}

export interface Scan {
  id: string;
  fileName: string;
  mimeType: string;
  /** File size in bytes */
  fileSize: number;
  width: number;
  height: number;
  verdict: Verdict;
  /** Confidence in the verdict, 0–100 */
  confidence: number;
  /** Probability the image is fake/AI generated, 0–100 */
  fakeProbability: number;
  /** Probability the image is real, 0–100 */
  realProbability: number;
  /** Time taken to process in milliseconds */
  processingMs: number;
  /** Per-feature signals from the model that influenced the verdict */
  signals: Signal[];
  /** A small data-URL thumbnail of the analyzed image for display in history. */
  previewDataUrl: string;
  createdAt: string;
}

export interface Stats {
  totalScans: number;
  realCount: number;
  fakeCount: number;
  avgConfidence: number;
  avgProcessingMs: number;
  /** Reported model accuracy on the validation set, 0–100 */
  accuracy: number;
  last24hScans: number;
}

export interface TimeseriesPoint {
  /** ISO date (YYYY-MM-DD) */
  date: string;
  real: number;
  fake: number;
}

export interface ConfidenceBucket {
  /** Confidence range label (e.g. "50-60%") */
  bucket: string;
  count: number;
}

export type ListScansParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type AnalyzeImageBody = {
  /** The image file to analyze (PNG, JPG, JPEG, WEBP). */
  image: Blob;
};

export type GetStatsTimeseriesParams = {
  /**
   * @minimum 1
   * @maximum 90
   */
  days?: number;
};
